### ISSUE TITLE
Handling of new values of categorical predictor for prediction

### ISSUE THREAD

**Issue by ElSyli0** [JeffreyRacine/R-Package-crs#11]
Hello ! I would like to know if there is a way to handle new attribute for categorical predictor in the prediction process.
For instance, let's suppose the dataset we use to build the model shows only the attributes "A" and "B" for the categorical predictor z_i. Once the model is built, if z_i has the attribute "C" for a new point we want to make a prediction, an error occurs saying there is an uknown level.

Thanks for your time !

**Comment by JeffreyRacine** [comment]
Greetings,

Thanks for your interest in the package. To answer your question, certainly!

You will use something predicated on the following:

> x <- ordered(c("A","B","C"))
> x
[1] A B C
Levels: A < B < C
> x <- ordered(x,levels=c(levels(x),"D"))
> x
[1] A B C
Levels: A < B < C < D

(note that even though in the data for x there are only 3 levels, the variable gets cast as being ordered having 4 levels)

So, using your example, when making a prediction with training and evaluation data you will do something like the following (here x is presumed ordered with levels "A" and "B"):

foo <- npreg(y~x,data=data.train)
x.eval <- c("A","C")
data.eval <- data.frame(x=ordered(x.eval,levels=c(levels(x),"C") ## IMPORTANT - training and evaluation predictors must have the same names, hence x= !!!
predict(foo,newdata=data.eval)

Or, if you are splitting a dataset into training and evaluation, save the levels prior to splitting (e.g., xlevels <- levels(x.fullsample)) then use these in the levels= call above...

One thing to note - if your levels are ordered but not alphabetically ordered (e.g., if income has levels "low", "middle", "high" - by default R will use alphabetical order hence the ordered variable will be "high" < "low" < "middle") then you definitely want to specify the levels in desired order to avoid any issues (e.g., x <- ordered(income,levels=c("low","middle","high"))

> x <- ordered(c("low","middle","high"))
> x
[1] low    middle high
Levels: high < low < middle
> x <- ordered(c("low","middle","high"),levels=c("low","middle","high"))
> x
[1] low    middle high
Levels: low < middle < high

Hope this helps!
