### ISSUE TITLE
Partially additive bases?

### ISSUE THREAD

**Issue by tcovert** [JeffreyRacine/R-Package-crs#4]
Suppose I have two sets of continuous predictors, X1 and X2.  Is there a way to tell `crs` to form a tensor basis on X1 and a separate tensor basis on X2, without any interactions between the two sets of predictors?  I am trying to implement the method in Newey, Powell and Vella (ECMA 1999), in which the X1's are (potentially) endogenous variables and the X2's are the residuals from a first stage projection of the X1's onto a set of instruments.  Thanks in advance for any suggestions.

**Comment by JeffreyRacine** [comment]
Greetings,

The default basis is a B-spline as you likely appreciate... the default is an additive model (basis = c("additive","tensor","glp","auto"))... so it is B(X1)+B(X2) where B() is the B-spline basis... 

But I am afraid I don't follow you... if I have a tensor basis for a single variable that is still a polynomial isn't it? That is, if B(X1)=(x1,x1^2,x1^3), then taking all possible combinations of these three columns still delivers a polynomial but of a higher order... or do I need to go for a coffee?

So the default which is B(X1)+B(X2) may do what you wish. With data-driven selection of the polynomial and the option prune=TRUE it will only keep the relevant bases... 

Hope this helps, and apologies if I misunderstood...

**Comment by tcovert** [comment]
Sorry if I was unclear in my initial question (which I can now see in re-reading).  

I'm imagining that X1 is a set variables (X11 and X12, for a 2d example) and X2 is a second set (X21 and X22).  I'd like the sum of the two respective tensor product bases for the X1 variables.  That is, if they were plain polynomials of order two, the tensor set for the X1 variables would be X11 + X12 + X11 * X12 + X11^2 + X12^2 and there would be a similar set for the X2 variables.  

Is there a way to tell `crs` to give me these terms, but no terms involving, say, X11 * X21?

**Comment by JeffreyRacine** [comment]
Apologies, I see now that you said "sets of"... 

You can use the function gsl.bs() to manually construct what you need... but crs() lacks the ability to do this unfortunately...

Jeff
