### ISSUE TITLE
Can't install with Intel compiler

### ISSUE THREAD

**Issue by tnagler** [JeffreyRacine/R-Package-crs#5]
First of all, thanks for all your great work on the np and crs packages.

I cannot use crs on my university's computing cluster, because ICC fails with the error messages reported below. gcc and clang (tested locally) seem to be fine.

#### Environment
* OS: SUSE Linux Enterprise Server 11 SP4
* Compiler: icpc (ICC) 16.0.4 20160811
* R: version 3.3.1 (2016-06-21)  (yeah I know it's old)

#### Error message
```
nomad_src/Evaluator_Control.cpp(3761): error: more than one instance of overloaded function "isnan" matches the argument list:
            function "isnan(double)"
            function "std::isnan(double)"
            argument types are: (const double)
      if ( isnan( fsmooth.value() ) || isnan( Psmooth.value() ) )
           ^

nomad_src/Evaluator_Control.cpp(3802): error: more than one instance of overloaded function "isnan" matches the argument list:
            function "isnan(double)"
            function "std::isnan(double)"
            argument types are: (const double)
              if ( ! isnan( fsmooth.value() ) && ! isnan( Psmooth.value() ) )
                     ^
```
#### Suggestion
Replacing all `isnan()` with `std::isnan()` should do the job.

**Comment by JeffreyRacine** [comment]
Greetings Thomas,

My partner in crime Zhenghua just pushed a fix that might work... your patch is not compatible with some versions of Microsoft Visual Studio C++ which could cause issues. The current fix gets around this, and if you would be kind enough to see whether Zhenghua's fix is ICC compatible and report that would be appreciated.

Regardless, thanks for the kind words and for taking the time to diagnose this issue.

Jeff

**Comment by tnagler** [comment]
Unfortunately, I can't even compile the new version locally. Error msg:

```
In file included from ./sgtelib_src/Matrix.hpp:35:0,
                 from ./sgtelib_src/Surrogate.hpp:29,
                 from ./sgtelib_src/Surrogate_Factory.hpp:31,
                 from ./sgtelib_src/sgtelib.hpp:31,
                 from ./nomad_src/Sgtelib_Model_Manager.hpp:56,
                 from ./nomad_src/Mads.hpp:61,
                 from ./nomad_src/nomad.hpp:51,
                 from snomadr.h:51,
                 from snomadr.cpp:32:
./sgtelib_src/Surrogate_Utils.hpp: In function ‘bool crs_isnan(double)’:
./sgtelib_src/Surrogate_Utils.hpp:61:13: error: redefinition of ‘bool crs_isnan(double)’
 inline bool crs_isnan ( double x ) { return x != x; }
             ^
In file included from ./nomad_src/Cache_Point.hpp:52:0,
                 from ./nomad_src/Cache.hpp:61,
                 from ./nomad_src/Barrier.hpp:52,
                 from ./nomad_src/Evaluator_Control.hpp:52,
                 from ./nomad_src/Search.hpp:51,
                 from ./nomad_src/Quad_Model_Evaluator.hpp:52,
                 from ./nomad_src/Single_Obj_Quad_Model_Evaluator.hpp:53,
                 from ./nomad_src/Quad_Model_Search.hpp:53,
                 from ./nomad_src/Mads.hpp:52,
                 from ./nomad_src/nomad.hpp:51,
                 from snomadr.h:51,
                 from snomadr.cpp:32:
./nomad_src/Eval_Point.hpp:58:13: note: ‘bool crs_isnan(double)’ previously defined here
 inline bool crs_isnan ( double x ) { return x != x; }
             ^
```
I opened a PR with a possible fix (#7), tested locally on ubuntu + gcc and on the cluster with ICC.

**Comment by JeffreyRacine** [comment]
Greetings Thomas,

Zhenghua has pushed a patch that hopefully addresses the issue... thanks again for bringing this to our attention, for your patches, and would you be kind enough to test and confirm?

Thanks!

**Comment by tnagler** [comment]
Hi Jeffrey,

everything seems to be working now (tested again locally on ubuntu + gcc and on the cluster with ICC). Thanks to you and Zhenghua for the quick help.
