### ISSUE TITLE
compilation error on Alpine Linux

### ISSUE THREAD

**Issue by bastistician** [JeffreyRacine/R-Package-crs#9]
Installing crs on Alpine Linux fails with "'timeval' was not declared in this scope".
The following patch fixes this:
```diff
diff -ur orig/src/sgtelib_src/Surrogate_Utils.hpp patched/src/sgtelib_src/Surrogate_Utils.hpp
--- orig/src/sgtelib_src/Surrogate_Utils.hpp	2021-02-01 03:56:08.000000000 +0100
+++ patched/src/sgtelib_src/Surrogate_Utils.hpp	2021-10-27 09:52:11.978919611 +0200
@@ -54,6 +54,7 @@
 #define isdigit(x) _isdigit(x)
 //#define isinf(x) (!_finite(x))
 #else
+#include <sys/time.h>
 #include <unistd.h>
 #endif
 ///////////
```

Note that this issue has already been addressed in sgtelib upstream via <https://github.com/bbopt/sgtelib/commit/222606960ec5918eb0f7e4af7a8a4a691333067d>.
It would be nice if this small fix could be considered for the next release.

**Comment by JeffreyRacine** [comment]
Greetings,

Thanks ever so much for taking the time to create this patch. File is patched and on next package update will be rectified, and in the meantime presume you are able to function with the patch.
